{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "final_space": true,
  "blocks": [
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "powerline",
          "foreground": "brightgreen",
          "background": "black",
          "properties": {
            "text": "▛ UZ-{{ .HostName }} "
          }
        },
        {
          "type": "path",
          "style": "powerline",
          "foreground": "black",
          "background": "brightgreen",
          "properties": {
            "style": "folder",
            "mapped_locations": {}
          }
        },
        {
          "type": "git",
          "style": "powerline",
          "foreground": "brightgreen",
          "background": "black",
          "properties": {
            "branch_icon": "⟨⟨ ",
            "fetch_status": true
          }
        }
      ]
    },
    {
      "type": "prompt",
      "alignment": "left",
      "segments": [
        {
          "type": "text",
          "style": "plain",
          "foreground": "brightgreen",
          "properties": {
            "text": "▙ ⟐ "
          }
        }
      ]
    }
  ]
}
